### ISSUE TITLE
Doesn't work with relative paths

### ISSUE THREAD

**Issue by ghoshnirmalya** [mzohaibqc/react-app-rewire-antd-theme#1]
If you host an app using this plugin on **gh-pages**, it doesn't work since it uses a path like **https://usernam.github.io/repo-name** and the generated **color.less** has a path like **https://username.github.io/color.less** instead of **https://username.github.io/repo-name/color.less**.

Can this be fixed please?

**Comment by mzohaibqc** [comment]
Hi @ghoshnirmalya, you are right, it should have option to user custom color.less path. I'll add that

**Comment by mzohaibqc** [comment]
@ghoshnirmalya I just looked into underlying webpack plugin's docs and saw that you can add `publicPath` key in config. In your case if will be `publicPath: '/repo-name'` something like that. Let me know if it you still face any issue.

**Comment by mzohaibqc** [comment]
@ghoshnirmalya Let me know if this fixed your problem or not?

**Comment by wahidshafique** [comment]
This does not seem to affect things for me, when rebuilding, the generated html does not prepend ./ to the color.less style sheet.

**Comment by mzohaibqc** [comment]
@wahidshafique Can you show me the config/options for this plugin?

**Comment by wahidshafique** [comment]
The SVN location looks something like this

http://svn.pl/svn/projects/tools/bug-table/build/index.html

I run ```yarn build``` and it always generates this: 

![image](https://user-images.githubusercontent.com/9141395/43645976-8c74aef0-9701-11e8-867f-8fc61cf494f6.png)

So each time I want to deploy, I have to manually set that to ./color.less

Here is the config file: 
![image](https://user-images.githubusercontent.com/9141395/43645894-41e79fe6-9701-11e8-8214-547df8c36698.png)

**Comment by mzohaibqc** [comment]
@ghoshnirmalya @wahidshafique I've updated this package. Use `npm i react-app-rewire-antd-theme@1.1.3` and then you can use `publicPath: "."` in options so it will be added in `color.less` file path to make it relative path like `href="./color.less"`

Let me know if it worked for you or not, I tested this and it worked for me.

**Comment by wahidshafique** [comment]
Yup, worked perfectly, thanks!
