### ISSUE TITLE
NPM link?

### ISSUE THREAD

**Issue by yairEO** [mzohaibqc/react-app-rewire-antd-theme#2]
There are no NPM/Yarn installation instruction nor a link to NPM

**Comment by sli** [comment]
https://www.npmjs.com/package/react-app-rewire-antd-theme

**Comment by mzohaibqc** [comment]
@yairEO @sli Author of this package here. I would recommend using `antd-theme-webpack-plugin`

Here is the example to follow
https://github.com/mzohaibqc/antd-theme-webpack-plugin/tree/master/examples/customize-cra

Here is demo
https://mzohaibqc.github.io/antd-theme-webpack-plugin/index.html

**Comment by mzohaibqc** [comment]
This package will be depricated since it is not being updated. Use the core script or core webpage plugin.
