### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by xenobardok** [mzohaibqc/react-app-rewire-antd-theme#3]
I followed each step listed in your medium post. Nothing happens! Colors.less file is not generated too. Let me know if you're still maintaining this repo. Thanks!

**Comment by mzohaibqc** [comment]
@SunilJamkatel It should work but I would suggest you to use [antd-theme-webpack-plugin](https://github.com/mzohaibqc/antd-theme-webpack-plugin) which is up to date and  easy to integrate.

Here is a live demo
https://mzohaibqc.github.io/antd-theme-webpack-plugin/index.html

And here is code for this demo
https://github.com/mzohaibqc/antd-theme-webpack-plugin/tree/master/examples/customize-cra

Don't forget to read the `README.md` before you start coding

**Comment by xenobardok** [comment]
Hi @mzohaibqc, at this point I have explored all your repos and examples trying to solve why my configuration is not working. lol. 

For the webpack solution, I don't see a webpack configuration on my project, should I create one myself?

**Comment by mzohaibqc** [comment]
Are you using `create-react-app` ?

**Comment by xenobardok** [comment]
yes

**Comment by mzohaibqc** [comment]
Then above mentioned example is for you. I've used `customize-cra` package to customize `create-react-app` configurations and added theme plugin. Just clone the repository and run that project

**Comment by xenobardok** [comment]
The repo runs flawlessly when you clone it and run. However, I was wanting to get a simple implementation working. Please let me know if I'm missing something here.

`config-overrides.js`

```
const path = require("path");
const fs = require("fs");
const {
  override,
  fixBabelImports,
  addLessLoader,
  addWebpackPlugin,
} = require("customize-cra");
const AntDesignThemePlugin = require("antd-theme-webpack-plugin");
const { generateTheme, getLessVars } = require("antd-theme-generator");

const defaultVars = getLessVars(
  "./node_modules/antd/lib/style/themes/default.less"
);
const darkVars = {
  ...getLessVars("./node_modules/antd/lib/style/themes/dark.less"),
  "@primary-color": defaultVars["@primary-color"],
};
const lightVars = {
  ...getLessVars("./node_modules/antd/lib/style/themes/compact.less"),
  "@primary-color": defaultVars["@primary-color"],
};
fs.writeFileSync("./src/dark.json", JSON.stringify(darkVars));
fs.writeFileSync("./src/light.json", JSON.stringify(lightVars));

const options = {
  stylesDir: path.join(__dirname, "./src/styles"),
  antDir: path.join(__dirname, "./node_modules/antd"),
  varFile: path.join(__dirname, "./src/styles/variables.less"),
  mainLessFile: path.join(__dirname, "./src/styles/index.less"),
  themeVariables: Array.from(
    new Set([
      "@primary-color",
      "@secondary-color",
      "@text-color",
      "@text-color-secondary",
      "@heading-color",
      "@layout-body-background",
      "@btn-primary-bg",
      "@layout-header-background",
      "@border-color-base",
      "@select-item-selected-option-color",
      ...Object.keys(darkVars),
      ...Object.keys(lightVars),
    ])
  ),
  generateOnce: false, // generate color.less on each compilation
};

module.exports = override(
  fixBabelImports("import", {
    libraryName: "antd",
    libraryDirectory: "es",
    style: true,
  }),
  addWebpackPlugin(new AntDesignThemePlugin(options)),
  addLessLoader({
    javascriptEnabled: true,
    modifyVars: { "@primary-color": "#25b864" },
  })
);
```


Created two files with name `index.less` and `variables.less` in src/styles


imported index.less in index.js .

I'm trying to make this file work.

`ColorInput.js`

```
import React from "react";
import { Row, Col, Input, Button } from "antd";
// const { getLessVars } = require("react-app-rewire-antd-theme");

class ColorInput extends React.Component {
  state = { vars: { "@primary-color": "#dddddd" } };
  onChange = (e) => {
    const color = e.target.value;
    console.log(color);

    if (color.match(/^#[a-f0-9]{3,6}$/i)) {
      console.log("color matched");

      const vars = this.state.vars;
      vars["@primary-color"] = color;
      console.log(vars);

      this.setState({ vars });
    }
  };
  updateVars = () => {
    window.less.modifyVars(this.state.vars).then(() => {
      console.log("Theme updated successfully");
    });
  };
  render() {
    console.log();

    return (
      <Row>
        <Col xs={16}>
          Primary Color: <Input onChange={this.onChange} />
        </Col>
        <Col xs={24}>
          <Button type="primary" onClick={this.updateVars}>
            Update Vars
          </Button>
        </Col>
      </Row>
    );
  }
}
export default ColorInput;
```

Hope you find something. Thanks for the help!

**Comment by mzohaibqc** [comment]
@SunilJamkatel You did not tell what is not working? What's the error? What exactly is not clear to you?

**Comment by xenobardok** [comment]
@mzohaibqc  sorry for not being clear. All the code listed here were taken from your repos. I am guessing that the input on `ColorInput` react class takes hex values and updates the primary color of the antd when you press the button. However, this does not happen. Any valid hex color value entered in the input field does not reflect changes on the app. I do receive the log on console `Theme updated successfully` with no changes on the color. I received an error message of 404 of the app not able to find colors.less. Hope I'm clear now.

**Comment by xenobardok** [comment]
Hi @mzohaibqc , any ideas? Let me know if you need additional details.

**Comment by mzohaibqc** [comment]
> I received an error message of 404 of the app not able to find colors.less. Hope I'm clear now.

When you know the reason then you should try to fix that. `color.less` file should be in `public` folder. Just follow the examples and there will be no issue.

**Comment by xenobardok** [comment]
By my understanding, `color.less` should be generated on every code compilation. I'm just wanting to know what part of my config is not working. I tried all your examples and all your packages. Nothing seems to be generating the `color.less` file.

**Comment by xenobardok** [comment]
Anyone who has the same issue please note that you'll need `create-react-rewire` and it doesn't work on `create-react-app`.
Issue solved.

**Comment by mzohaibqc** [comment]
@SunilJamkatel If someone is using Ant Design, it is obvious that he needs to eject create-react -app or use tools like create-react-app-rewired or customize-cra to override CRA configurations. It is mentioned here 
https://ant.design/docs/react/use-with-create-react-app
